/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface WordGameDictionary : NSObject {
	char* dictionaryCharStr;
	int* wordIndices;
	int wordCount;
}
-(bool)isValidWord:(id)word;
-(int)binarySearchWord:(const char*)word size:(int)size;
-(int)compareCharString:(const char*)string wordIndex:(int)index;
-(void)loadDictionaryFast;
-(void)assertDictHasWord:(id)word shouldHaveWord:(BOOL)word2;
-(void)assertDictHasWord:(id)word;
-(void)loadDictionary;
-(void)writeOutPropertyList;
-(void)dealloc;
@end

